In [2]:
import numpy as np
import pandas as pd
import cvxpy as cp
import math

In [71]:
def phi(n,t):
    return np.array([[4 - 3*math.cos(n*t), 0, 0, (1/n) * math.sin(n*t), (2/n) * (1 - math.cos(n*t)),0],
                 [6*(math.sin(n*t)-n*t),1, 0, -1*(2/n)*( 1 - math.cos(n*t)), (1/n)*(4*math.sin(n*t) - 3*n*t),0],
                 [0,0,math.cos(n*t),0,0,(1/n)*math.sin(n*t)],
                 [3*n*math.sin(n*t),0,0,math.cos(n*t),2*math.sin(n*t),0],
                 [-6*n*(1-math.cos(n*t)),0,0,-2*math.sin(n*t), 4*math.cos(n*t)-3, 0], 
                 [0,0,-1*n*math.sin(n*t), 0, 0, math.cos(n*t)]])

# inital x
x_0 = np.array([0,0,0,1,0,0]).reshape((6,1))

total = 10
m = 100


def move(u):
    delta = 1
    n = (2*np.pi) / 96400
    k = phi(n,0)@x_0
    for i in range(1,total):
        k = k + phi(n,i) @ np.array([[0],[0],[0],[u[i][0]*delta],[u[i][1]*delta],[u[i][2]*delta]])
    return np.sum(k**2)

x = cp.Variable((total,3))
objective = cp.Minimize(move(x))
constraints = []

for i in range(total):
    constraints += [x[i][0]**2 + x[i][1]**2 + x[i][2]**2 <= m]
prob = cp.Problem(objective, constraints)
prob.solve()
print(x.value)


[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-4.97968856e-01 -3.24293806e-05  0.00000000e+00]
 [-3.65043420e-01 -4.75905631e-05  0.00000000e+00]
 [-2.54168131e-01 -4.97113412e-05  0.00000000e+00]
 [-1.62952102e-01 -4.24971681e-05  0.00000000e+00]
 [-8.33646329e-02 -2.71784236e-05  0.00000000e+00]
 [-1.02296290e-02 -4.00431060e-06  0.00000000e+00]
 [ 5.88699327e-02  2.68638932e-05  0.00000000e+00]
 [ 1.25232150e-01  6.53089639e-05  0.00000000e+00]
 [ 1.89624626e-01  1.11238277e-04  0.00000000e+00]]
